// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig, env } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: env("DATABASE_URL"),
//     directUrl : env("DATABASE_URL_POOLED")
//   },
// });

import "dotenv/config";
import { defineConfig } from "prisma/config";
import { PrismaPg } from "@prisma/adapter-pg";

export default defineConfig({
  // ✅ REQUIRED FOR prisma migrate
  datasource: {
    url: process.env.DATABASE_URL,
  },

  // ✅ REQUIRED FOR runtime (Neon pooler)
  datasources: {
    db: {
      adapter: new PrismaPg({
        connectionString: process.env.DATABASE_URL_POOLED,
      }),
    },
  },
});



console.log("POOLED URL exists:", !!process.env.DATABASE_URL_POOLED);